services:
  - type: web
    name: swinir-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python enhance.py
    autoDeploy: true
    plan: free
    region: oregon



