services:
  - type: web
    name: swinir-enhancer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python enhance.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.12




